runall

diff --git a/src/c/smoke/runall b/src/c/smoke/runall
--- a/src/c/smoke/runall
+++ b/src/c/smoke/runall
@@ -4,5 +4,10 @@ chmod 774 crux-test.pl
 ln -fs test.fasta existing.fasta
 
 ./crux-test.pl crux-test.cmds 1>out 2>error
-tail -n6 out
+if [ $? ]
+then echo "Test aborted"
+else
+	tail -n6 out
+fi
+
 echo "  Test output in the file 'out'.  Error messages in 'error'."
