set build backend to Ninja

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,6 +37,9 @@ jobs:
         run: |
              cd "${{runner.workspace}}/build"
              echo Building in $(pwd)
+             which ninja || echo "ninja not found in PATH" && exit 1
+             # Set the generator to Ninja.
+             cmake -G "Ninja"
              cmake --build . --config $BUILD_TYPE 
 
       - name: Build package
